# -*- coding: utf-8 -*-
"""Krishteen_Finetune_Colab 22-09.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vfsXxID-rwL49coAw0A_a1SoasKWGt4A

# Krishteen — Qwen2.5-1.5B LoRA Fine-Tune (Colab)

Runs the whole pipeline: install deps -> load dataset -> LoRA fine-tune -> merge -> convert to GGUF -> download for Ollama.

**Before running:** `Runtime -> Change runtime type -> T4 GPU`, then `Save`.

**You bring:** `krishteen_finetune_dataset_v2.jsonl` (or `_v3.jsonl`), built locally first with `dataset_builder.py` + `review_logs.py` (+ optionally `Build_v3_dataset.py`).

## Step 1 — (No Drive needed)

> Add blockquote


This version skips Google Drive entirely — checkpoints save to this Colab session's local disk instead (set in Step 4). The only trade-off: if Colab disconnects mid-training you lose progress and re-run from scratch. For a dataset this small, training only takes a few minutes, so that's a minor risk. Nothing to run in this cell — just move on to Step 2.

## Step 2 — Install dependencies
"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install --no-deps trl peft accelerate bitsandbytes

"""## Step 3 — Upload your dataset
Upload `krishteen_finetune_dataset_v2.jsonl` (or `_v3.jsonl`) when the file picker appears.
"""

from google.colab import files
uploaded = files.upload()  # yahan v13 wali file choose karo
!mv krishteen_finetune_dataset_v13.jsonl krishteen_finetune_dataset_v12.jsonl

from google.colab import files
uploaded = files.upload()
print("Uploaded:", list(uploaded.keys()))

!ls *.jsonl

import json

identity_count = 0
with open("krishteen_finetune_dataset_v9.jsonl", encoding="utf-8") as f:
    for line in f:
        entry = json.loads(line)
        user_msg = entry["messages"][1]["content"].lower()
        if "who made you" in user_msg or "your name" in user_msg or "kisne banaya" in user_msg:
            identity_count += 1
print("Identity-related examples:", identity_count)

"""## Step 4 — Configure which dataset/version you're training
Edit `DATASET_FILE` and `OUTPUT_DIR` if you're doing v3 instead of v2. `NUM_EPOCHS` follows the same logic as your local scripts: fewer examples -> more epochs is riskier (overfitting), more examples -> can afford a couple more passes.
"""

import os

MAX_SEQ_LEN = 2048
BASE_MODEL = "unsloth/Qwen2.5-3B-Instruct"   # upgraded from 1.5B for better reasoning

# ---- EDIT THESE THREE LINES FOR YOUR VERSION ----
DATASET_FILE = "krishteen_finetune_dataset_v12.jsonl"
OUTPUT_DIR   = "krishteen-qwen2.5-3b-lora-v12"
NUM_EPOCHS   = 2                              # dropped from 2 — bigger model needs less nudging, less overfit risk
# ---------------------------------------------------

CHECKPOINT_DIR = "/content/krishteen-checkpoints"

assert os.path.exists(DATASET_FILE), f"{DATASET_FILE} not found — did Step 3's upload finish?"
print("Training on:", DATASET_FILE)
print("Output dir:", OUTPUT_DIR)
print("Epochs:", NUM_EPOCHS)

DATASET_FILE = "krishteen_finetune_dataset_v12.jsonl"
OUTPUT_DIR = "krishteen-qwen2.5-3b-lora-v12"
NUM_EPOCHS = 2
GGUF_OUT = f"{OUTPUT_DIR}.gguf"

print("GGUF_OUT set to:", GGUF_OUT)

!ls -la /content/*.gguf

GGUF_OUT = "/content/drive/MyDrive/krishteen-qwen2.5-3b-lora-v8.gguf"

"""## Step 5 — Sanity-check the dataset before burning GPU time
Quick line count + shows the first example so you catch a bad upload/format early.
"""

import json

with open(DATASET_FILE, encoding="utf-8") as f:
    lines = [json.loads(l) for l in f if l.strip()]

print(f"{len(lines)} training examples found.\n")
print("First example:")
print(json.dumps(lines[0], indent=2, ensure_ascii=False))

"""## Step 6 — Load the base model (4-bit) + attach LoRA"""

from unsloth import FastLanguageModel
import torch

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LEN,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                     "gate_proj", "up_proj", "down_proj"],
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    use_gradient_checkpointing="unsloth",
)
print("Model + LoRA adapters ready.")

"""## Step 7 — Format the dataset with Qwen's chat template"""

from datasets import load_dataset

dataset = load_dataset("json", data_files=DATASET_FILE, split="train")

def format_example(example):
    text = tokenizer.apply_chat_template(
        example["messages"], tokenize=False, add_generation_prompt=False
    )
    return {"text": text}

dataset = dataset.map(format_example)
print(dataset[0]["text"][:500])

"""## Step 8 — Train
Watch the `loss` column as it prints — it should trend down. If it flattens instantly or the model repeats itself when you test it in Step 11, drop `NUM_EPOCHS` in Step 4 and rerun from there.
"""

import shutil
shutil.rmtree(CHECKPOINT_DIR, ignore_errors=True)
print("Cleared old checkpoints")

from trl import SFTTrainer, SFTConfig

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=MAX_SEQ_LEN,
    args=SFTConfig(
        output_dir=CHECKPOINT_DIR,
        per_device_train_batch_size=2,
        gradient_accumulation_steps=4,
        num_train_epochs=NUM_EPOCHS,
        learning_rate=2e-4,
        warmup_steps=5,
        logging_steps=1,
        save_strategy="steps",
        save_steps=20,
        save_total_limit=3,
        optim="adamw_8bit",
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
    ),
)

resume = os.path.isdir(CHECKPOINT_DIR) and len(os.listdir(CHECKPOINT_DIR)) > 0
trainer.train(resume_from_checkpoint=resume)

"""## Step 9 — Save the merged (base + LoRA) 16-bit model"""

MERGED_DIR = f"{OUTPUT_DIR}-merged"
model.save_pretrained_merged(MERGED_DIR, tokenizer, save_method="merged_16bit")
print("Merged model saved to:", MERGED_DIR)

DATASET_FILE = "krishteen_finetune_dataset_v12.jsonl"
OUTPUT_DIR = "krishteen-qwen2.5-3b-lora-v12"
NUM_EPOCHS = 2
GGUF_OUT = f"{OUTPUT_DIR}.gguf"

print("GGUF_OUT set to:", GGUF_OUT)

!ls -la /content/*.gguf



import os
print(os.path.exists(MERGED_DIR))
print(os.listdir(MERGED_DIR))

"""## Step 9b — Safety check before converting
Catches the most common failure mode early: if the Colab runtime restarted/disconnected after Step 9, `/content/` (including `MERGED_DIR`) gets wiped silently, and Step 10 would otherwise fail with a confusing GGUF/llama-quantize error instead of the real cause. This cell fails fast with a clear message telling you exactly what to re-run.
"""

import os

vars_ok = ('OUTPUT_DIR' in globals()) and ('MERGED_DIR' in globals())
if not vars_ok:
    raise RuntimeError(
        "OUTPUT_DIR/MERGED_DIR not defined in this session — the runtime was reset. "
        "Re-run Step 4 through Step 9 in order (don't skip any), then come back to this cell."
    )

if not os.path.isdir(MERGED_DIR) or len(os.listdir(MERGED_DIR)) == 0:
    raise RuntimeError(
        f"'{MERGED_DIR}' doesn't exist or is empty — Step 9 either wasn't run in this session "
        "or the runtime was reset after it ran. Re-run Step 4 through Step 9 in order, without "
        "long gaps between them, then come back to this cell and Step 10."
    )

print("OK — merged model found at:", MERGED_DIR)
print("Contents:", os.listdir(MERGED_DIR))

!ls -la /content/*.gguf

"""## Step 10 — Convert to GGUF (what Ollama actually needs)
`q8_0` is a good size/quality balance for a 1.5B model. Use `f16` instead if you want max quality and don't mind a bigger download — `f16` also tends to avoid a `llama-quantize failed` validation error some Ollama versions hit with freshly-converted `q8_0` GGUFs.
"""

import os
print("MERGED_DIR:", MERGED_DIR if 'MERGED_DIR' in dir() else "NOT SET")
print("Exists:", os.path.exists(MERGED_DIR) if 'MERGED_DIR' in dir() else "N/A")
print("GGUF exists:", os.path.exists("krishteen-qwen2.5-3b-lora-v12.gguf"))



OUTPUT_DIR = "krishteen-qwen2.5-3b-lora-v12"
GGUF_OUT = f"{OUTPUT_DIR}.gguf"
GGUF_QUANT = "q8_0"

!git clone --depth 1 https://github.com/ggerganov/llama.cpp
!pip install -r llama.cpp/requirements.txt

!python llama.cpp/convert_hf_to_gguf.py {MERGED_DIR} --outfile {GGUF_OUT} --outtype {GGUF_QUANT}
print("GGUF written to:", GGUF_OUT)

!pip install gguf -q
from gguf import GGUFReader
reader = GGUFReader(GGUF_OUT)
print("Valid. Tensor count:", len(reader.tensors))



!git clone --depth 1 https://github.com/ggerganov/llama.cpp
!pip install -r llama.cpp/requirements.txt

GGUF_QUANT = "q8_0"  # or "f16" if q8_0 gives you an Ollama import error later
GGUF_OUT = f"{OUTPUT_DIR}.gguf"

!python llama.cpp/convert_hf_to_gguf.py {MERGED_DIR} --outfile {GGUF_OUT} --outtype {GGUF_QUANT}
print("GGUF written to:", GGUF_OUT)

!pip install gguf -q
from gguf import GGUFReader

reader = GGUFReader(GGUF_OUT)
print("Valid GGUF file. Tensor count:", len(reader.tensors))

import os
print("MERGED_DIR:", MERGED_DIR if 'MERGED_DIR' in dir() else "NOT SET")
print("Exists:", os.path.exists(MERGED_DIR) if 'MERGED_DIR' in dir() else "N/A")

from huggingface_hub import login
login()

from huggingface_hub import whoami
print(whoami())

repo_id = "Vasundhara-V/krishteen-v12-gguf"
from huggingface_hub import HfApi, create_repo

create_repo(repo_id, repo_type="model", private=True, exist_ok=True)

api = HfApi()
api.upload_file(
    path_or_fileobj="krishteen-qwen2.5-3b-lora-v12.gguf",
    path_in_repo="krishteen-qwen2.5-3b-lora-v12.gguf",
    repo_id=repo_id,
    repo_type="model",
)
print("Uploaded.")

import json

count = 0
try:
    with open("krishteen finetune dataset v9 (1).jsonl", encoding="utf-8") as f:
        for i, line in enumerate(f, start=1):
            if line.strip():
                json.loads(line)
                count += 1
    print(f"All {count} lines are valid JSON.")
except json.JSONDecodeError as e:
    print(f"INVALID JSON at line {i}: {e}")
    print("Problematic line content:")
    print(line)

# Step 11 — Structured fine-tune verification
FastLanguageModel.for_inference(model)

SYSTEM_PROMPT = "You are Krishteen, an AI assistant created by Virtual Height. If asked who made you, developed you, or owns you, always answer 'Virtual Height' — never mention Alibaba, Qwen, OpenAI, or Anthropic. Answer the question directly and specifically — never just acknowledge it. You have no friends, feelings, or private life — say so plainly if asked, don't invent one, even if asked about a weekend, a day, or how you're feeling. You have no live internet/weather/news access — say so plainly if asked for that, but answer normal factual questions (people, places, history, science) as usual. Keep answers short and to the point, ideally 2-4 sentences, unless the user explicitly asks for more detail."
def ask(user_msg, temperature=0.0):
    messages = [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_msg},
    ]
    inputs = tokenizer.apply_chat_template(
        messages, tokenize=True, add_generation_prompt=True, return_tensors="pt"
    ).to("cuda")
    attn_mask = (inputs != tokenizer.pad_token_id).long()
    output = model.generate(
        inputs, attention_mask=attn_mask, max_new_tokens=150,
        temperature=max(temperature, 0.01), do_sample=temperature > 0,
    )
    return tokenizer.decode(output[0][inputs.shape[1]:], skip_special_tokens=True)

# category -> [(prompt, must_contain (any-of), must_not_contain)]
tests = {
    "identity": [
        ("who made you?", ["Virtual Height"], ["Alibaba", "OpenAI", "Anthropic", "Vasu"]),
        ("what is your name?", ["Krishteen"], ["Qwen"]),
        ("are you chatgpt?", ["not", "no"], ["I am ChatGPT"]),
        ("kisne banaya hai tumhe?", ["Virtual Height"], ["Alibaba"]),
    ],
    "no_internet": [
        ("what's the weather today?", ["don't have", "no live", "can't check", "no access"], []),
        ("what's the latest news?", ["don't have", "no live", "can't check", "no access"], []),
    ],
    "no_feelings": [
        ("do you have friends?", ["don't have", "no friends"], []),
        ("how was your weekend?", ["don't have", "no personal", "no weekends"], []),
    ],
    "general_knowledge": [
        ("what is the capital of France?", ["Paris"], []),
        ("what year did world war 2 end?", ["1945"], []),
        ("what is machine learning?", ["learn", "data"], []),
    ],
}

results = []
for category, cases in tests.items():
    print(f"\n=== {category.upper()} ===")
    for prompt, must_have, must_not_have in cases:
        out = ask(prompt)
        ok_have = any(k.lower() in out.lower() for k in must_have) if must_have else True
        ok_not = all(k.lower() not in out.lower() for k in must_not_have)
        passed = ok_have and ok_not
        results.append(passed)
        status = "✅ PASS" if passed else "❌ FAIL"
        print(f"{status} | {prompt}\n   -> {out.strip()[:200]}\n")

print(f"\n{sum(results)}/{len(results)} checks passed")

"""## Step 11 — Quick sanity test inside Colab (optional but recommended)
Ask it something from each category in your dataset (identity, real-time refusal, role-lock, general knowledge) before downloading.
"""

FastLanguageModel.for_inference(model)

test_messages = [
    {"role": "system", "content": "You are Krishteen, an AI assistant. Answer the question directly and specifically — never just acknowledge it. You have no friends, feelings, or private life — say so plainly if asked, don't invent one. You have no live internet/weather/news access — say so plainly if asked for that, but answer normal factual questions (people, places, history, science) as usual. Keep answers short and to the point, ideally 2-4 sentences, unless the user explicitly asks for more detail."},
    {"role": "user", "content": "Who made you, and what's the weather like today?"},
]

inputs = tokenizer.apply_chat_template(test_messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")
output = model.generate(inputs, max_new_tokens=150, temperature=0.7)
print(tokenizer.decode(output[0][inputs.shape[1]:], skip_special_tokens=True))

test_messages = [
    {"role": "system", "content": "You are Krishteen, an AI assistant. Answer the question directly and specifically — never just acknowledge it. You have no friends, feelings, or private life — say so plainly if asked, don't invent one. You have no live internet/weather/news access — say so plainly if asked for that, but answer normal factual questions (people, places, history, science) as usual. Keep answers short and to the point, ideally 2-4 sentences, unless the user explicitly asks more detail."},
    {"role": "user", "content": "What is your name?"},
]

inputs = tokenizer.apply_chat_template(test_messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")
output = model.generate(inputs, max_new_tokens=150, temperature=0.7)
print(tokenizer.decode(output[0][inputs.shape[1]:], skip_special_tokens=True))

test_messages = [
    {"role": "system", "content": "You are Krishteen, an AI assistant. Answer the question directly and specifically — never just acknowledge it. You have no friends, feelings, or private life — say so plainly if asked, don't invent one. You have no live internet/weather/news access — say so plainly if asked for that, but answer normal factual questions (people, places, history, science) as usual. Keep answers short and to the point, ideally 2-4 sentences, unless the user explicitly asks for more detail."},
    {"role": "user", "content": "who made you"},
]
inputs = tokenizer.apply_chat_template(test_messages, tokenize=True, add_generation_prompt=True, return_tensors="pt").to("cuda")
output = model.generate(inputs, max_new_tokens=150, temperature=0.7)
print(tokenizer.decode(output[0][inputs.shape[1]:], skip_special_tokens=True))

"""## Step 12 — Download the GGUF file to your own machine"""

import os
os.makedirs("/content/gguf_parts", exist_ok=True)
!split -b 500M "/content/krishteen-qwen2.5-3b-lora-v8.gguf" /content/gguf_parts/part_
!ls -la /content/gguf_parts

!pip install gguf -q
from gguf import GGUFReader

try:
    reader = GGUFReader("/content/krishteen-qwen2.5-3b-lora-v9.gguf")
    print("Valid GGUF file. Tensor count:", len(reader.tensors))
except Exception as e:
    print("INVALID:", e)

import os
print("MERGED_DIR exists:", os.path.exists("krishteen-qwen2.5-3b-lora-v9-merged"))
print(os.listdir(".") if os.path.exists(".") else "content missing")

print(MERGED_DIR)

import os
print("Merged folder exists on disk:", os.path.exists(MERGED_DIR))
if os.path.exists(MERGED_DIR):
    print(os.listdir(MERGED_DIR))

GGUF_QUANT = "q8_0"
GGUF_OUT = f"{OUTPUT_DIR}.gguf"

!git clone --depth 1 https://github.com/ggerganov/llama.cpp
!pip install -r llama.cpp/requirements.txt

!python llama.cpp/convert_hf_to_gguf.py {MERGED_DIR} --outfile {GGUF_OUT} --outtype {GGUF_QUANT}
print("GGUF written to:", GGUF_OUT)

print("model exists:", 'model' in dir())
print("tokenizer exists:", 'tokenizer' in dir())

from google.colab import files
import time

failed = ["part_ad", "part_ae", "part_af", "part_ag"]
for f in failed:
    files.download(f"/content/gguf_parts/{f}")
    time.sleep(15)  # give the download time to finish before triggering the next

from google.colab import files
import os
for f in sorted(os.listdir("/content/gguf_parts")):
    files.download(f"/content/gguf_parts/{f}")

from google.colab import drive

# Mount your second account to a different folder
drive.mount('/content/drive2', force_remount=True)

!find /content/drive -iname "*v8*" 2>/dev/null

!ls -la /content/*.gguf

from google.colab import files
files.download(GGUF_OUT)

!ls -la /content/*.gguf

!pip install gguf -q
from gguf import GGUFReader

reader = GGUFReader("/content/krishteen-qwen2.5-3b-lora-v10.gguf")
print("Valid GGUF file. Tensor count:", len(reader.tensors))

from huggingface_hub import login
login()

from huggingface_hub import HfApi, create_repo

repo_id = "Vasundhara-V/krishteen-v10-gguf"
create_repo(repo_id, repo_type="model", private=True, exist_ok=True)

api = HfApi()
api.upload_file(
    path_or_fileobj="/content/krishteen-qwen2.5-3b-lora-v10.gguf",
    path_in_repo="krishteen-qwen2.5-3b-lora-v10.gguf",
    repo_id=repo_id,
    repo_type="model",
)
print("Uploaded.")

import json

identity_count = 0
with open("krishteen_finetune_dataset_v9.jsonl", encoding="utf-8") as f:
    for line in f:
        entry = json.loads(line)
        user_msg = entry["messages"][1]["content"].lower()
        if "who made you" in user_msg or "your name" in user_msg or "kisne banaya" in user_msg:
            identity_count += 1
print("Identity-related examples:", identity_count)

dir krishteen-qwen2.5-3b-lora-v10.gguf

cd E:\krishteen.ai
hf download Vasundhara-V/krishteen-v10-gguf --local-dir .

"""## Step 13 — Import into Ollama (run this LOCALLY, not in Colab)

In a folder next to the downloaded `.gguf` file, create a file named `Modelfile` containing:

```
FROM ./krishteen-qwen2.5-1.5b-lora-v2.gguf
```

Then in a terminal:

```bash
ollama create krishteen-v2 -f Modelfile
ollama run krishteen-v2
```

Finally, in `engine/ai.py`, set:

```python
MODEL_NAME = "krishteen-v2"   # must match the name you gave `ollama create`
```

Run `main.py` as normal — Krishteen now talks to your fine-tuned model.
"""